services:

  # Database
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  # Interface
  adminer:
    image: adminer:4
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"

volumes:
  postgres-data: { }
