services:

  # Database
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"

  # Interface
  adminer:
    image: adminer:4
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"

volumes:
  mysql-data: { }
